### ISSUE TITLE
FilterShipMMSI filter not working

### ISSUE THREAD

**Issue by bdnorman** [aisstream/example#9]
Hello, I'm trying to use the FilterShipMMSI filter to limit the number of results a get but it doesn't seem to be working. It's still returning all ships in the region I specified. Payload is the following:
```
       subscribe_message = {
            "APIKey": AIS_API_KEY,
            "BoundingBoxes": [[[25.3668, 119.092], [21.985, 120.721]]],
            "FilterShipMMSI": ["416006181"]
        }
```

**Comment by aisstream** [comment]
The API is slightly confusing, the Json key is `FiltersShipMMSI` not `FilterShipMMSI`. We will note this down to accept MSSI's set in both keys `FilterShipMMSI` and `FiltersShipMMSI` for a future release.

**Comment by bdnorman** [comment]
@aisstream got it thank you!

**Comment by interfaith** [comment]
it seems to take forever to find the position of one vessel ? yet cranks out the whole list in a few hours ?
to find a vessel give the bound boxes within 100 miles ?.
I guess your service is only for vessels in port ?
